### ISSUE TITLE
USER STORY: Prep for Production

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#121]
As **Site Owner** I can **update my site settings** so that **it is fully functional for production**.

### Acceptance Criteria
- Acceptance Criteria 1: All settigns refer to Sarah Rae not developer/code institure
- Acceptance Criteria 2: All contact information
- Acceptance Criteria 2:
### Tasks
- [ ]  Activate Stripe
- [ ] Mailchimp Newsletter settings
- [ ]  Facebook/Instagram site live /launch
- [ ] stock management
- [ ] Packaging  work flow
- [ ] delivery work flow
