### ISSUE TITLE
Prep: Create Bug Log

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#2]
### Tasks
- [x] Create Spreadsheet

**Comment by mikerae** [comment]
As **Developer** I can **log bugs as they are discovered** so that **I can track their existance and plan their fix**.

### Acceptance Criteria
- Bug issues are created on GitHub
- Bug table is viewable in Project Bug Table

### Tasks
- [x] Create Bug Issue template on GitHub repo
- [x] Create Bug issues Bugs as they are identified
- [x] Create branch for bug issue when it is  readty to be owrked on
- [x] Commit bug fixing to branch
- [x] Merge branch to main after bug fix and testing.
- [x] Add comments to bug issue explaining the fix
