### ISSUE TITLE
USER STORY: Send Newsletter

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#23]
As **Site Owner** I can **send an email Newsletter to interested Site Users** so that **encourage a community of people interested in my work, and inform them of new initiatives.**.
ref #101 #23 #56 #51 #113  

### Acceptance Criteria
- Acceptance Criteria 1: User acceptance to receive newsletter recorded in user profile
- Acceptance Criteria 2: Attach Newsletter pdf to mailchimp email  for Site Owner
- Acceptance Criteria 3: Send Newsletter functionality to all users who have signed up
### Tasks
- [x] Task 1: Create newsletter app
- [x] Task 2: Create email with newsletter attachment functionality (upload)
- [x] Task 3: Send email functionality
