### ISSUE TITLE
USER STORY: Confirmation of Purchase email

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#38]
As **Shopper** I can **receive a confirmation of purchase email with contact details, delivery info and returns info included** so that **easily contact the artist after purchasing, and have the process of delivery and returns explained**.

### Acceptance Criteria
- Acceptance Criteria 1: Shopper receives a confirmation email on checkout
- Acceptance Criteria 2: Email contains summary of order
- Acceptance Criteria 2: Email contains contact site info 
### Tasks
- [x] Task 1: set up django email
- [x] Task 2: pass appropriate data to email
- [x] Task 3: send email on checkout
