### ISSUE TITLE
Prep: Create User Stories

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#4]
Itemise User Stories from consultations ith Sarah Rae

### Acceptance Criteria
- User stories created from dialogue with Sarah Rae  are viewable in Rednme
- A user story issue is created for each epic
- User Story issues are in GitHub project SarahRae Illustrations created for each  user story

### Tasks
- [x] Discuss and establish user stories with Sarah Rae
- [x] Record user stories in Readme
- [x] Create userstory issues in GitHub
