### ISSUE TITLE
USER STORY: Order Confirmation

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#41]
As **Shopper** I can ** view an order confirmation after checkout** so that **I can verify that I haven’t made any mistakes**.

### Acceptance Criteria
- Acceptance Criteria 1: Send confirmation email to purchaser with order details and contact info
### Tasks
- [ ] Task 1: Set up django email capability
- [ ] Task 2: Include order detail and contact info in email subject and body
- [ ] Task 3: Send email
- [ ] Test receipt of email
