### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#46]
As **Site User** I can **Easily register for an account** so that **I can easily make future purchases**.

### Acceptance Criteria
-There is opportunity to register an account on eery page
- There is opportunity to register an account on checkout

### Tasks
- [x] Set up allauth
- [x] Link to sign-up in Nav-Accounts
- [x] Link to sign-up in  Checkout
