### ISSUE TITLE
USER STORY: Login/Out

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#47]
As **Site User** I can **Easily login or log out ** so that **I can navigate the site incognito or as registered user as I prefer.**.

ref: #46 #49 
### Acceptance Criteria
- Login available in landing site
- Login/Logout available on evey page through nac bar

### Tasks
- [x] Set up Allauth
- [x] Link to Login on Landing page
- [x] Link to login in Acconts nav-bar
