### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#50]
As **Site User** I can ** have a personal user profile** so that **I can view my personal order history and order confirmations and save my payment information**.

### Acceptance Criteria
- Acceptance Criteria 1: User Profile exists for each registered user
- Acceptance Criteria 2: User profile showing shipping details and order history is viewable by registered user
- Acceptance Criteria 2: User profile shipping details are editable by  user
### Tasks
- [x] Task 1: create profile model
- [x] Task 2: populate user profile shipping details on purchase
- [x] Task 3: populate order history on purchase
