### ISSUE TITLE
USER STORY: SEO

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#53]
As **Site Owner** I can **optimise Search Engine Activity** so that **Increase my visibility on the web**.

### Acceptance Criteria
- Robitics file exists at correct sit elocation
- sitemap file exists at correct sit elocation
- metea tags exits on all pages:
- external links have rel tags
- 
### Tasks
- [x] Include a project robots.txt file
- [x] Include a project sitemap.xml file
- [x] Include project Descriptive meta tags
- [x] include project rel attributes on links to external resources
- [x] Validate using Lighthouse and score over 90 for SEO for each page
