### ISSUE TITLE
USER STORY: Facebook Buisness Page

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#55]
As **Site Owner** I can **link to a real Facebook business page, or a mockup of one.** so that **I can market within Facebook community**.

### Acceptance Criteria
- Acceptance Criteria 1: Facebook Buisness Page is created
- Acceptance Criteria 2: Link to Facebook Buisness Page is available in the footer
- Acceptance Criteria 2:  Facebook Buisness Page is documented in ReadME
### Tasks
- [x] Task 1: Create  Facebook Buisness Page
- [x] Task 2: Link Facebook Buisness Page in footer using external rel link, opens in new window
- [x] Task 3: Reference Facebook Buisness Page in Readme
