### ISSUE TITLE
USER STORY: Display Art Work

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#6]
As **Site Owner** I can **display my artwork** so that I can **raise my profile on the net**.

### Acceptance Criteria
- Artworks are displayed in carousel
- Artworks are displayed in Galley
-  I can select which artworks to display in carousel

### Tasks
- [x] Display artworks in Carousel
- [x] Allow artwork selection for carousel
- [x] Display artworks in Gallery
