### ISSUE TITLE
USER STORY:Display Art Works Carousel

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#72]
As **Site Owner** I can **display my art works in a carousel on the landing page** so that **people can immediately see some of my work as soon as they land on my site**.

### Acceptance Criteria
- Carousel of Art Work is displayed on 
- Acceptance Criteria 2:
- Acceptance Criteria 2:
### Tasks
- [ ] Show generic bootstrap carousel on landing page
- [ ] Show test images in carousel
- [ ] Create artWorks app with ArtWorks model
- [ ] Create appropriate Artworks context data for use in carousel
- [ ] Use Artworks context data to show images stored in ArtWorks database in carousel (javascript/context code)
