### ISSUE TITLE
USER STORY: Digital Art Works Database

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#73]
As **Site Owner** I can **store and manage my digital artworks in a database** so that **I can **.

### Acceptance Criteria
- Digital Art Works are stored in database
- Digital Art Works are viewable by Site Owner
- Digital Art works can be created, read, updated and deleated by Site Owner
### Tasks
- [x] Create Digital Art Works Model in ArtWorks app
- [x] store 3 test artworks
- [x] Load model with example catalogue of Digital Art Works
- [x] admin CRUD functionality
