### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#74]
As **Site owner** I can **display my Digital Art Works in a Gallery** so that **people can view my catalogue of Digital Art Works**.

### Acceptance Criteria
- Galley area of Site
- All Art Works are displayed
- Single detailed Art Works are displayed with full info
- Sort and search functionality
- CRUD catalogue functionality
### Tasks
- [ ] Gallery all Digital Art Works view
- [ ] Gallery all Digital Art Work detail view
- [ ] Navigation to  and within Gallery
- [ ] Gallery CRUD management
