### ISSUE TITLE
USER STORY: View Digital Artworks

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#75]
As **Site User** I can **view Digital Artworks** so that **appreciate the art work of the Site Owner, become aware of the work, and consider purchasing and commissioning work**.

### Acceptance Criteria
- Digital Art Works can be viewed in Carousel on landing  page
- Digital Art Works summary can be viewed in Gallery
- Digital Art Work detail can be viewed in Gallery
- Digital Art Works can be searched and sorted
### Tasks
- [x] Connect Digital Art Works to carousel on landing page
- [x] Digital Art Works summary view in Gallery
- [x] Digital Art Work detail  view in Gallery
