### ISSUE TITLE
USER STORY: SKU Generation

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#88]
As **Site Owner** I can **automatically generate a unique SKU when I add a new product** so that **each product can be properly identified**.

### Acceptance Criteria
- Existing products have proper SKUs
- On add product, SKU is automatically generated
- On add category, and sub category, SKU sub identifiers are set
- SKUs are non editable
- SKUs are unique
- reference Digital Artwork where appropriate
### Tasks
- [ ] Set Category sub-SKU fields & populate existing categories
- [ ]  Set Subcategory sub-SKU fields & populate existing subcategories
- [ ] write view logic for adding product
- [ ] ensure 'add product' form submission works
