### ISSUE TITLE
USER STORY:Stripe: Migrate to using fully integrating Stripe

### ISSUE THREAD

**Issue by mikerae** [mikerae/sarah-rae-illustrations#90]
As **site owner** I can **fully integrate with Stripe** so that **use Stripe's powerful invoicing, reporting and analytics**.

### Acceptance Criteria
- All CRUD functionality on products is integrated with Stripe
- All CRUD functionality on Users is integrated with Stripe
- Stripe Analytics are accessable by Site owner
### Tasks
- [ ] Migrate from cardElement to paymentElement
- [ ] Integrate Product Id:
- [ ] Integrate Price ID:
- [ ] Integrate Users with Customers:
- [ ] Integrate Users home and billing address on payments
- [ ] set up Analytics
- [ ] display analytics
